### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jimfilippou** [rojo2/passport-cookie#7]
Just add this file and TS warnings will go away 
![image](https://user-images.githubusercontent.com/6877046/100385791-5eaca880-302c-11eb-9116-b9a363f5b958.png)

**Comment by jimfilippou** [comment]
Did you just close the issue without fixing it?

**Comment by AzazelN28** [comment]
Open a PR with the file you already have and I will merge it.

Next time try to open the PR directly (especially if you already have the file written) instead of sending a screenshot of the source code, I think it will take you the same amount of time (or even less because you don't have to draw red arrows).
